version: '3'

services:
  nginx:
      image: nginx:1.13
      ports:
        - "80:8000"
      volumes:
        - ./nginx/conf:/etc/nginx/conf.d
        - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
        - ./static:/static
      depends_on:
        - python

  # db:
  #     image: mysql:5.7
  #     container_name: db
  #     command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  #     ports:
  #       - "3306:3306"
  #     env_file: ./.env
  #     environment:
  #       MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
  #       MYSQL_DATABASE: $MYSQL_DATABASE
  #       MYSQL_USER: $MYSQL_USER
  #       MYSQL_PASSWORD: $MYSQL_PASSWORD
  #       TZ: 'Asia/Tokyo'
  #     volumes:
  #       - ./mysql:/var/lib/mysql
  #       - ./sql:/docker-entrypoint-initdb.d

  python:
      build: ./python
      env_file: ./.env
      command: uwsgi --socket :8001 --module config.wsgi --py-autoreload 1 --logto /tmp/mylog.log
      volumes:
        - ./src:/code
        - ./static:/static
      expose:
        - "8001"
      # depends_on:
        # - db
