# Generated by Django 2.2.14 on 2020-10-02 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10, verbose_name='ティッカー')),
                ('unit', models.IntegerField(blank=True, default=0, null=True, verbose_name='保有数量')),
                ('avg_price', models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=10, null=True, verbose_name='平均取得単価')),
                ('upper_price', models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=10, null=True, verbose_name='利確ライン')),
                ('lower_price', models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=10, null=True, verbose_name='損切りライン')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
